nvme: Check timestamp format result and increase string size
linux-nvme/nvme-cli pull request #1599
Opened 2022-07-07 19:33 UTC by ikegami-t

Since the default size is possible to be exceeded for a locale date and time.

Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>

2022-07-08 08:09 UTC, igaw requested changes
Good catch. Though I think I would just make the default size of the buffer bigger (as in this patch to 320 bytes or something more aligned as 256) and test for the return code of `strftime` and set the buffer to `'-\0'`.  I think the realloc part is a bit over engineered.

2022-07-08 12:42 UTC, ikegami-t commented
> Good catch. Though I think I would just make the default size of the buffer bigger (as in this patch to 320 bytes or something more aligned as 256) and test for the return code of `strftime` and set the buffer to `'-\0'`. I think the realloc part is a bit over engineered.

Thanks for your review comment. Fix the patch as suggested.

2022-07-11 10:02 UTC, igaw approved these changes

2022-07-11 10:02 UTC, igaw commented
Nice cleanups! Thanks a lot!

2022-07-11 10:02 UTC, merged