nvme-print: added missing fguid to json id-ctrl output
linux-nvme/nvme-cli pull request #1661
Opened 2022-09-01 06:24 UTC by skasero

- add fguid to json
- removed some whitespace

2022-09-01 07:00 UTC, igaw commented
Hmm, I think this is colliding with https://github.com/linux-nvme/nvme-cli/pull/1652

You might want to coordinate the work on fguid.

2022-09-02 00:25 UTC, pierrelabat requested changes

2022-09-02 01:10 UTC, skasero reviewed
The error I got with uuid_string_t:
`error: ‘uuid_string_t’ undeclared (first use in this function)`

2022-09-02 06:38 UTC, igaw commented on nvme-print.c
> +		fr[sizeof(ctrl->fr) + 1], subnqn[sizeof(ctrl->subnqn) + 1], fguid[37];
Please also add a define for the magic number. BTW, isn't this missing the NULL char?

2022-09-02 06:40 UTC, igaw commented
And merge these two patches into one while at it. Don't want to merge the development history. Thanks.

2022-09-07 09:38 UTC, igaw commented
Should be fixed with https://github.com/linux-nvme/nvme-cli/commit/78b7ad235507ddd59c75c7fcc74fc6c927811f87  and https://github.com/linux-nvme/nvme-cli/commit/5acfc7215917f94d31fd05be7958114d7b3a85d6. I completely forgot about this PR when reviewing/working on #1652. Didn't want to steal your commit. Sorry.

2022-09-07 09:38 UTC, closed without merging