nvme: support security-recv and security-send over nvme-mi
linux-nvme/nvme-cli pull request #1744
Opened 2022-12-21 08:10 UTC by jinliangw

We cannot use wrapper method as other commands because the API between inband and nvme-mi are not compatible.

Signed-off-by: Jinliang Wang <jinliangw@google.com>

Tested:
```
# ./nvme security-recv -n 0 --secp=1 --spsp=0x0001 --size=512 --al=512 mctp:1,16:0
NVME Security Receive Command Success
       0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
0000: 00 00 00 b4 00 00 00 01 00 00 00 00 00 00 00 00 "................"
0010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 "................"
0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 "................"
0030: 00 01 10 0c 51 00 00 00 00 00 00 00 00 00 00 00 "....Q..........."
0040: 00 02 10 0c 09 00 00 00 00 00 00 00 00 00 00 00 "................"
0050: 00 03 10 1c 01 00 00 00 00 00 00 00 00 00 02 00 "................"
0060: 7f ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00 "................"
0070: 02 01 10 0c 00 00 00 21 04 00 00 00 00 00 00 00 ".......!........"
0080: 02 02 10 0c 00 00 00 08 00 a0 00 00 00 00 00 01 "................"
0090: 02 03 10 10 10 00 00 02 01 00 04 00 21 00 00 00 "............!..."
00a0: 00 00 00 00 04 03 22 10 20 00 00 00 00 00 00 21 "......"........!"
00b0: 00 00 00 20 00 00 00 01 00 00 00 00 00 00 00 00 "................"
```

2022-12-22 09:04 UTC, igaw commented on nvme-wrap.c
> +	}
So why can't we use `do_admin_args_op()` here as well? The only difference I was able to spot is that you are not setting the command timeout for `NVME_DEV_DIRECT` case.

Ah, I see it now, the function name suffix do not match: `nvme_security_receive` vs `nvme_mi_admin_security_recv`.

2022-12-22 09:06 UTC, igaw requested changes
Could you add the default timeout value to the `NVME_DEV_DIRECT`, so it's more consistent. Also please add a small comment in this function why we cannot use `do_admin_args_op`.

Thanks.

2022-12-22 18:04 UTC, jinliangw commented
Done, thanks for the suggestion!

2022-12-23 15:30 UTC, igaw approved these changes

2022-12-23 15:31 UTC, merged

2022-12-23 15:31 UTC, igaw commented
Thanks.