RFC: xnvme backend support
linux-nvme/nvme-cli pull request #1873
Opened 2023-03-23 09:49 UTC by vikash-k5

Extended “struct nvme_dev” with the following device-handle types:

* struct dev_handle
* enum nvme_dev_type

The  ‘dev_handle' contains ‘struct xnvme_dev*’, file-descripter and ‘nvme_dev_type’ to manage library-side dispatch.

Adding  ‘open_dev_xnvme(struct nvme_dev **devp, char *devname)’ function to open xNVMe library device handle and same being passed to ‘libnvme’ through ‘struct dev_handle’.

This xnvme plugin can work on different platform such as linux, freebsd and even windows. As well as this can work with different driver on linux(kernel and userspace driver such as SPDK)

Note: this will require libnvme changes, which can be found here
https://github.com/linux-nvme/libnvme/pull/600

2023-03-24 11:54 UTC, igaw requested changes
It looks more of the transport abstraction should be in libnvme.

2023-03-24 11:54 UTC, igaw commented on meson.build
> +libxnvme_dep = dependency('xnvme', version: '>=0.2.0', required: true)
This should be guarded by meson option setup option to disable it completely, see `json-c` as example. Some folks really don't like if we add hard dependencies.

2023-03-24 11:54 UTC, igaw commented on nvme-wrap.c
> +	if (d->type == NVME_DEV_DIRECT || d->type == NVME_DEV_XNVME)	\
The complete `nvme-wrap.c` file shouldn't be needed after introducing the transport abstraction.

2023-03-24 11:54 UTC, igaw commented on nvme.c
> +
Please avoid doing whitespace changes or adding too many newlines here.

2023-03-24 11:54 UTC, igaw commented on nvme.c
>  static int get_dev(struct nvme_dev **dev, int argc, char **argv, int flags)
I thought we are going to use the newly introduce transport abstraction from the library through out nvme-cli? Ideally we have this open device in libnvme, no?

2023-03-24 11:54 UTC, igaw commented on nvme.c
> +		.hnd		= dev_fd(dev),
`dev_fd` should be renamed of course.

2023-03-24 11:54 UTC, igaw commented on nvme.h
> +static inline struct dev_handle* __dev_fd(struct nvme_dev *dev, const char *func, int line)
as previously said, this function should be renamed.

2023-08-08 16:41 UTC, vikash-k5 commented
Created new PR addressing review comments

2023-08-08 16:41 UTC, closed without merging