nvme-print: Add support for EGFEAT, Domain Identifier, TEGCAP and UEGCAP
linux-nvme/nvme-cli pull request #2035
Opened 2023-08-18 20:25 UTC by ikegami-t

2023-08-21 13:02 UTC, igaw requested changes

2023-08-21 16:01 UTC, ikegami-t commented on nvme-print-json.c
> +	nvme_uint128_t host_write_cmds = le128_to_cpu(endurance_group->host_write_cmds);
Split the whitespace changes as a separated patch and also fixed to add to print domain_identifier correctly.

2023-09-04 16:42 UTC, igaw commented
- Rebased to current master
- Add libnvme wrap update

2023-09-04 16:42 UTC, igaw approved these changes

2023-09-04 16:46 UTC, merged

2023-09-04 16:46 UTC, igaw commented
Sorry took a bit longer. Too much work...