nvme/plugins: Add performance stats v2
linux-nvme/nvme-cli pull request #2176
Opened 2023-12-27 10:14 UTC by jinhuahuang2021

Add performance stats v2

2024-01-18 16:37 UTC, igaw requested changes
some nitpicking:
- split the white space changes from the new code 
- pay more attention on proper alignment
- use the new cleanup helpers for `struct nvme_dev` allocations

Rest looks okay.

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +										__u8 *raw_val)
I'd prefer if you could split out white space changes into a separate patch. Mixing janitor updates and new code is making the review harder that it needs to be.

Anyway, when shortening overlong lines, please align the arguments or use two spaces as indent, e.g.

```c
static void get_memblaze_new_smart_info(struct nvme_p4_smart_log *smart, int index, __u8 *nm_val,
					__u8 *raw_val)
```

or 

```c
static void get_memblaze_new_smart_info(struct nvme_p4_smart_log *smart, int index, __u8 *nm_val,
		__u8 *raw_val)
```

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +			int48_to_long(raw));
Here the `int48_to_long` argument could align with the opening '('.

Obviously, this is also true for all cases below.

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +		   *raw, ", cnt: ", int48_to_long(raw+1));
This change is not needed as the line is already properly align.

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +	struct command *cmd, struct plugin *plugin)
Indent these two lines with double tap, so the arguments do not align with the single tab indented variable declearations.

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +	char *desc = "Get Memblaze additional smart log, and show it.";
Overlong strings are okay to be one line. This is an exception but if the shortened help text is also fine. Either way you like it.

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +							  &smart_log);
Not needed.

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +									struct plugin *plugin)
Too many tab indention for the arguments.

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +		((*(buf + 2) & 0xff) == 0xad) && ((*(buf + 3) & 0xff) == 0xde))
Not needed

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +	dev_close(dev);
You could use the cleanup helper and then you could just remove the `dev_close`.

```c
        _cleanup_nvme_dev_ struct nvme_dev *dev = NULL;
```

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +	// Get the configuration
Please avoid non meaningful comments. It's obvious from the code what is happening. This clutters just the code. Some for the rest of the comments in this function.

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +								struct plugin *plugin)
Indention is off.

2024-01-18 16:37 UTC, igaw commented on plugins/memblaze/memblaze-nvme.c
> +		//
remove this empty comment

2024-01-26 04:05 UTC, jinhuahuang2021 commented
The PR need more change, I will update it together.

2024-03-07 13:36 UTC, igaw commented
Do you still work on this?

2024-03-08 02:18 UTC, jinhuahuang2021 commented
Yes, we are :)

2024-03-08 14:50 UTC, igaw commented
Okay, not sure what the update from yesterday means. FWIW, there shouldn't be any merges in the PR. Just rebase your changes to the latest upstream version and update the commit from there. Hope this helps.

2024-03-14 03:53 UTC, jinhuahuang2021 commented
This PR contains various modifications, which makes it confusing.
I close this PR and split it to small PRs.

2024-03-14 03:53 UTC, jinhuahuang2021 commented
This PR contains various modifications, which makes it confusing.
I close this PR and split it to small PRs.

2024-03-14 03:53 UTC, closed without merging